#!/bin/bash
#
# You can move this file to any location you want
# and run 'Xonotic Server Tools' with this script.
#
# You need to fix the path.
# Fix 'please-fix-me' to the real location of xstools.sh.

bash /please-fix-me/xstools.sh $@
