#!/bin/bash
#
# You can move this file to any location you want
# and run 'Xonotic Server Tools' with this script.
#
# And you need to fix the path.
# fix 'please-fix-me' to the real location 

bash /please-fix-me/xstools.sh $@
